# Generated by Django 5.2.7 on 2025-10-29 12:22

import django.db.models.deletion
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_folder_storedfile_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='last_downloaded_at',
            new_name='last_download_at',
        ),
        migrations.AddField(
            model_name='storedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.folder'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='original_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='stored_file',
            field=models.FileField(max_length=1024, upload_to=storage.models.user_directory_path),
        ),
    ]
