# Generated by Django 5.2.7 on 2025-10-29 13:54

import django.db.models.deletion
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='last_download_at',
            new_name='last_downloaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='download_count',
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.folder'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='public_link_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='stored_file',
            field=models.FileField(upload_to=storage.models.user_directory_path),
        ),
    ]
